// Every user-facing string lives here (design_system rule 10), so i18n can be
// added later without hunting literals.

export const strings = {
  app: {
    name: "Mask",
    settings: "Settings",
    updateTo: (version: string) => `Update to v${version}`,
    updating: "Updating…",
  },
  status: {
    stopped: "Stopped",
    starting: "Starting",
    running: "Live",
    error: "Error",
  },
  devices: {
    panelTitle: "Devices",
    microphone: "Microphone",
    output: "Output (virtual mic)",
    monitor: "Monitor",
    monitorOff: "Off",
    start: "Start",
    stop: "Stop",
    rescan: "Re-scan devices",
    noInputSelected: "Pick a microphone first",
    inputMeter: "In",
    outputMeter: "Out",
    noDevices: "No audio devices found",
    cableMissingBanner: "No virtual cable installed. Calls will not hear your voice.",
    cableMissingAction: "Open setup guide",
  },
  effects: {
    panelTitle: "Effects",
    custom: "Custom",
    pitch: "Pitch",
    formant: "Formant",
    semitonesUnit: "st",
    saveAsPreset: "Save as preset",
    deletePreset: "Delete",
    confirmDelete: "Click again to delete",
  },
  soundboard: {
    panelTitle: "Soundboard",
    import: "Import sounds",
    stopAll: "Stop all",
    empty: "No sounds yet",
    emptyHint: "Import audio files and play them into your call",
    rename: "Rename",
    volume: "Volume",
    delete: "Delete",
    broken: "File missing. Re-import this sound.",
    importFilterName: "Audio",
  },
  onboarding: {
    title: "Route your voice into calls",
    explain:
      "Mask needs a virtual microphone so Discord, Zoom and friends can hear your modified voice. Mask can install one for you — Windows will ask for permission once.",
    installAuto: "Install virtual microphone",
    installDownloading: "Downloading the signed driver…",
    installElevating: "Waiting for Windows permission…",
    installReboot:
      "Installed, but Windows needs a restart to enable it. Restart your PC, then reopen Mask.",
    installBlocked: (problemCode: number) =>
      problemCode === 52
        ? "Windows blocked the driver: its signature isn't accepted on this PC (Secure Boot / Memory Integrity). Restarting won't fix it."
        : `Windows blocked the driver (Device Manager code ${problemCode}). Restarting won't fix it.`,
    installBlockedAction: "Install VB-Cable instead — it's Microsoft-signed and works everywhere:",
    installErrorPrefix: "Install failed:",
    retry: "Try again",
    manualHint: "Prefer to install manually? VB-Cable also works:",
    downloadVbCable: "Download VB-Cable",
    downloadAlt: "Virtual-Audio-Driver (what Mask installs)",
    waiting: "After installing manually, come back here.",
    rescan: "Check again",
    detected: "Cable detected!",
    detectedBody: "Mask will send your voice to it. One last step on the call side:",
    callAppGuide:
      'In Discord / Zoom, set the microphone to "Virtual Mic Driver by MTT" (or "CABLE Output" if you installed VB-Cable).',
    testHint: "Speak. If the Out meter moves, the route works.",
    skip: "Skip for now",
    next: "Next",
    done: "Finish",
  },
  vc: {
    panelTitle: "AI Voices",
    backend: { directMl: "GPU (DirectML)", cuda: "GPU (CUDA)", cpu: "CPU (slow)" },
    setup: "Download AI components",
    setupHint: "One-time download of the voice encoder and pitch models.",
    downloading: "Downloading",
    empty: "No AI voices yet",
    emptyHint: "Import an RVC voice model (.onnx) to transform your voice identity",
    importModel: "Import voice",
    importClone: "Import cloned voice",
    activate: "Use",
    deactivate: "Turn off",
    active: "Active",
    loading: "Loading voice…",
    fallback: "AI voice paused (too slow). Try a larger chunk size.",
    pitchOffset: "Pitch offset",
    chunk: "Latency vs stability",
    deleteModel: "Delete",
    needsPipeline: "Start the microphone first",
    consentTitle: "Consent required",
    consentBody:
      "Clones are for fun between friends. Confirm the voice's owner agreed to this clone being used.",
    consentCheckbox: "The owner of this voice gave me consent",
    cloneGuide: "How to train a clone (guide)",
    modelFilterName: "ONNX model",
    namePrompt: "Voice name",
    confirmImport: "Import",
    cancel: "Cancel",
  },
  errors: {
    pipelineStart: "Could not start the microphone.",
    showDetail: "Details",
  },
  links: {
    vbCable: "https://vb-audio.com/Cable/",
    virtualAudioDriver: "https://github.com/VirtualDrivers/Virtual-Audio-Driver/releases",
    cloneGuide: "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
  },
} as const;
